expenses/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

app_name = "expenses"

router = routers.DefaultRouter()
router.register(r'expense', views.ExpenseViewSet)
router.register(r'category', views.CategoryViewSet)

urlpatterns = [
    path('', views.expense_list, name="list"),
    path('json/', views.expense_list_json, name="json"),
    path('create/', views.expense_create, name="create"),
    path('<int:id>/', views.expense_detail, name="detail"),
    path('<int:id>/star/', views.expense_star, name="star"),

    path('category/', views.CategoryListView.as_view(), name="category_list"),

    # path('category-better/', views.BetterCategoryListView.as_view(), name="category_list_better"),

    path('api/', include(router.urls)),

]

kkiss/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('expenses.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

expenses/models.py
from django.conf import settings
from django.core import validators
from django.db import models


class Category(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='categories')
    name = models.CharField(max_length=300)

    class Meta:
        unique_together = (
            ('user', 'name'),
        )
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Expense(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='expenses')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='expenses')
    title = models.CharField(max_length=300)
    amount = models.DecimalField(decimal_places=2, max_digits=10, validators=[
        validators.MaxValueValidator(1_000_000),
        validators.MinValueValidator(0.50),
    ])
    date = models.DateField()
    description = models.TextField(blank=True)
    is_star = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def is_expensive(self):
        return self.amount > 50

expenses/views.py
from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseNotAllowed, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from rest_framework import viewsets

from expenses.models import Expense, Category
from expenses.serializers import ExpenseSerializer, CategorySerializer


class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        exclude = (
            'user',
            'is_star',
        )


def get_expense_form(user, data=None):
    form = ExpenseForm(data)
    form.fields['category'].queryset = user.categories.all()
    return form


@login_required()
def expense_create(request):
    if request.method == "POST":
        form = get_expense_form(request.user, request.POST)
        if form.is_valid():
            form.instance.user = request.user
            o = form.save()
            return redirect("expenses:list")
    else:
        form = get_expense_form(request.user)
    return render(request, "expenses/expense_form.html", {
        'form': form,
    })


@login_required()
def expense_list(request):
    q = request.GET.get('q')
    qs = request.user.expenses.order_by('-date')  # related_name on the Expense.user model field!
    if q:
        qs = qs.filter(title__icontains=q)
    return render(request, "expenses/expense_list.html", {
        'object_list': qs,
    })


@login_required()
def expense_star(request, id: int):
    if request.method != "POST":
        return HttpResponseNotAllowed(["POST"])

    import time
    import random
    time.sleep(random.randint(1, 2))
    # TODO: reliable toggle :-)
    o = get_object_or_404(Expense, user=request.user, id=id)
    o.is_star = not o.is_star
    o.save()
    # return HttpResponse(f"star star-{'on' if o.is_star else 'off'}")
    return JsonResponse({
        'star': o.is_star,
    })


@login_required()
def expense_detail(request, id: int):
    return render(request, "expenses/expense_detail.html", {
        'object': get_object_or_404(Expense, user=request.user, id=id),
    })


@login_required()
def expense_list_json(request):
    q = request.GET.get('q')
    qs = request.user.expenses.order_by('-date')  # related_name on the Expense.user model field!
    if q:
        qs = qs.filter(title__icontains=q)
    return JsonResponse({'items': ExpenseSerializer(qs, many=True).data})
    # return JsonResponse({'items': [ExpenseSerializer(o).data for o in qs]})
    # return JsonResponse({'items': [{
    #     'id': o.id,
    #     'amount': o.amount,
    #     'title': o.title,
    #     'date': o.date,
    #     'category': {
    #         'id': o.category.id,
    #         'name': o.category.name,
    #     },
    # } for o in qs]})


# @login_required()
# def category_list(request):
#     qs = request.user.categories.all()
#     return render(request, "expenses/category_list.html", {
#         'object_list': qs,
#     })

# class based views (CBV)


# class CategoryListView(View):
#     template_name = "my_template.html"
#     def get(self, request, *args, **kwargs):
#         return render(request, "my_template.html")
# return render(request, self.template_name)

# class CategoryListView(TemplateView):
#     template_name = "my_template.html"
#     foo = 123
#
#     def bar(self):
#         return 10 * "!"
#
# class BetterCategoryListView(CategoryListView):
#     def bar(self):
#         return super().bar().center(50, "?")
#

class CategoryListView(LoginRequiredMixin, ListView):
    # queryset = Category.objects.order_by('-name')
    paginate_by = 5

    def get_queryset(self):
        return self.request.user.categories.all()


# class BetterCategoryListView(CategoryListView):
#     def get(self, request):
#         qs = self.get_queryset()
#         return JsonResponse({'items': self.get_queryset()})


# class ExpenseViewSet(viewsets.ModelViewSet):
class ExpenseViewSet(viewsets.ModelViewSet):
    queryset = Expense.objects.all()
    serializer_class = ExpenseSerializer


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

expenses/templates/base.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <title>
        {% block title %}
            TITLE!!!
        {% endblock %}
        /
        💰 Kesef Kiss 💰
    </title>
</head>
<body>
<div class="container">

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url "expenses:list" %}">KesefKiss</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "expenses:create" %}">Create</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0 ml-auto" action="{% url "expenses:list" %}">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-dark my-2 my-sm-0" type="submit">Search</button>
            </form>
            <ul class="navbar-nav ml-lg-3">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">{{ user }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "logout" %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "login" %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </nav>

    {% block content %}
        +++!!!CONTENT!!!+++
    {% endblock %}

    <div id="endoftext">
        Copyright 2020 :-)
    </div>

    <script src="{% static "js/jquery-3.5.1.slim.min.js" %}"></script>
    <script src="{% static "js/popper.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.js" %}"></script>
    {% block scripts %}

    {% endblock %}

</div>
</body>
</html>

expenses/templates/expenses/category_list.html
{% extends "base.html" %}
{% load static bootstrap4 %}

{% block title %}
    My Categories
{% endblock %}

{% block content %}
    <h1>
        My Categories ({{ object_list.count }})
    </h1>

    <ul class="list-group">
        {% for object in object_list %}
            <li class="list-group-item">
                {{ object }}
                {{ object.user }}
            </li>
        {% endfor %}
    </ul>

    {% bootstrap_pagination page_obj %}

{% endblock %}

expenses/templates/expenses/expense_detail.html
{% extends "base.html" %}

{% block title %}
    Expense #{{ object.id }}
{% endblock %}

{% block content %}
    <h1>
        Expense #{{ object.id }}
    </h1>

    <ul>
        <li>
            {{ object.category }}: {{ object.title }}
        </li>
        <li>
            ${{ object.amount }}
        </li>
        <li>
            Date: {{ object.date }}
        </li>
        <li>
            Description: {{ object.description|linebreaksbr }}
        </li>
    </ul>
{% endblock %}

expenses/templates/expenses/expense_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}
    Create New expense
{% endblock %}

{% block content %}
    <h1>
        Create New Expenses
    </h1>

    <form method="post" novalidate>
        {% csrf_token %}

        {% bootstrap_form form %}

        <button>Create</button>

    </form>


{% endblock %}

expenses/templates/expenses/expense_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    My Expenses
{% endblock %}

{% block content %}
    <h1>
        My Expenses ({{ object_list.count }})
    </h1>

    <table class="table table-striped table-hover">
        <tr>
            <th>
                #
            </th>
            <th>
                Category
            </th>
            <th>
                Title
            </th>
            <th>
                Amount
            </th>
            <th>
                Date
            </th>
        </tr>
        {% for object in object_list %}
            <tr>
                <td>
                    <a href="{% url "expenses:detail" object.id %}">
                        {{ object.id }}
                    </a>
                    <span class="star {% if object.is_star %}star-on{% else %}star-off{% endif %}" data-url="{% url "expenses:star" object.id %}">
                        <img class="full" src="{% static "svg-icons/star-fill.svg" %}" alt="" width="18" height="18" title="Unstar">
                        <img class="empty" src="{% static "svg-icons/star.svg" %}" alt="" width="18" height="18" title="Star">
                        <img class="reloader" src="{% static "svg-icons/star-half.svg" %}" alt="" width="18" height="18" title="Refreshing....">
                    </span>
                </td>
                <td class="expense_title nice">
                    {{ object.category }}
                </td>
                <td class="expense_title nice">
                    {{ object.title }}
                </td>
                <td>
                    ${{ object.amount }}
                </td>
                <td class="nice">
                    {{ object.date }}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

{% block scripts %}
    <script src="{% static "js/expense_list.js" %}"></script>
{% endblock %}